### PR TITLE
Add/meeting notes 2

### PR DESCRIPTION
**Pull request by vsoch**
This is the second document for meeting notes, note that the first hasn't been added yet #13 so I figured I could add both commits here.

### CODE REVIEW

**Comment by vbatts** [comment]
I wish this were automated :thinking:

**Comment by vsoch** [comment]
I think it could be if someone is brave to add the integration with hack.md (I am not).

**Comment by vbatts** [comment]
there are no APIs for this :-\
This would be a fairly manual process for someone to do everytime.

**Comment by vsoch** [comment]
But I have an idea! If I can get a download link for the markdown, I can create a scheduled GitHub workflow to retrieve the file (at some frequency) and then update it's version in the repository here, and then either push to a branch directly (e.g., master) or push to an update branch that opens a PR with the changes (and then the maintainer would just look over and merge). I've done it a bunch of times for other stuffs, it just comes down to getting a static export programmatically.

**Comment by vbatts** [comment]
ha. as long as it isn't overly fragile.

**Pull request closed without merging**
